import Link from "next/link";

function Mark({ small = false }: { small?: boolean }) {
  return <svg className={small ? "payreconMark small" : "payreconMark"} viewBox="0 0 40 40" aria-hidden="true"><rect x="1" y="1" width="38" height="38" rx="11" fill="#2b83ea"/><path d="M11 13h12a5 5 0 0 1 0 10H16v5h-5V13Zm5 5v1h7a.5.5 0 0 0 0-1h-7Z" fill="white"/><path d="M22 13h6v4h-6zM22 23h6v5h-6z" fill="#b8dcff"/></svg>;
}

export default function LandingPage() {
  return <main className="landingPage">
    <header className="landingNav"><Link className="landingBrand" href="/"><Mark/> <span>PayRecon<small>PAYMENTS OPERATIONS</small></span></Link><nav><a href="#workflow">How it works</a><a href="#trust">Trust &amp; controls</a><Link className="loginLink" href="/login">Sign in</Link><Link className="landingCta" href="/login">Open workspace <span>→</span></Link></nav></header>
    <section className="landingHero"><div className="heroCopy"><div className="heroEyebrow"><i/> FINANCE OPERATIONS, CONNECTED</div><h1>Close the books<br/>with evidence,<br/><em>not guesswork.</em></h1><p>Bring your order ledger, Razorpay settlements, and bank credits together. PayRecon links the records, checks payout math, and gives your team a clear queue for the exceptions that need a human.</p><div className="heroActions"><Link className="landingCta large" href="/login">Open local workspace <span>→</span></Link><a className="quietLink" href="#workflow">Explore the workflow <span>↓</span></a></div><div className="heroFootnote"><span className="tinyCheck">✓</span> Exact identifiers · Traceable evidence · Human-reviewed decisions</div></div>
      <div className="heroVisual" aria-label="Illustration of a reconciliation worklist"><div className="visualTop"><div><small>RECONCILIATION RUN</small><b>September settlement close</b></div><span className="visualComplete"><i/> READY FOR REVIEW</span></div><div className="visualKpis"><div><small>Orders linked</small><b>48 <i>/ 50</i></b></div><div><small>Settlements checked</small><b>12 <i>/ 12</i></b></div><div><small>Open exceptions</small><b className="kpiAmber">03</b></div></div><div className="visualRows"><div className="visualRow heading"><span>REFERENCE</span><span>RECONCILIATION</span><span>STATUS</span></div><div className="visualRow"><span><b>ORD-9082</b><small>pay_Nx92••</small></span><span>Order → settlement → bank</span><span className="rowMatched">✓ Matched</span></div><div className="visualRow"><span><b>ORD-9083</b><small>pay_Nx94••</small></span><span>Bank credit is short by ₹42.48</span><span className="rowReview">Review</span></div><div className="visualRow"><span><b>UTR-783010</b><small>Settlement group</small></span><span>Two payments in one payout</span><span className="rowMatched">✓ Matched</span></div></div><div className="visualNote"><span>✦</span> Every result links back to its source rows.</div></div>
    </section>
    <section className="landingProof" id="workflow"><div><b>01</b><span><strong>Bring your three ledgers</strong><small>Upload files for the same reporting period.</small></span></div><div><b>02</b><span><strong>Match on real identifiers</strong><small>Payment IDs, purchase references, and UTRs.</small></span></div><div><b>03</b><span><strong>Resolve the exceptions</strong><small>Review the evidence and export a worklist.</small></span></div></section>
    <section className="landingTrust" id="trust"><div className="trustHeading"><small>BUILT FOR FINANCE OPERATORS</small><h2>Automation with boundaries.</h2><p>PayRecon does the repetitive joins and arithmetic. Your finance team remains in control of unresolved records.</p></div><div className="trustTiles"><article><span className="trustGlyph">⌁</span><b>Identity-led matching</b><p>No automatic match from amount, date, or customer name alone.</p></article><article><span className="trustGlyph">◎</span><b>Reproducible calculations</b><p>Settlement arithmetic uses integer paise and a disclosed rounding tolerance.</p></article><article><span className="trustGlyph">▤</span><b>Source-row evidence</b><p>Each finding carries the records and next review step that support it.</p></article></div></section>
    <footer className="landingFooter"><Link className="landingBrand" href="/"><Mark small/> <span>PayRecon</span></Link><span>Independent local reconciliation workspace · Not a Razorpay product</span><Link href="/login">Sign in →</Link></footer>
  </main>;
}
